/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import Clases.cliente;
import Clases.encuesta;
import Clases.Validaciones;
import javax.swing.JOptionPane;

/**
 *
 * @author GALATEA
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form promedioEncuesta
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulojLabel = new javax.swing.JLabel();
        nombrejLabel = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellidojLabel = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        numclienteJLabel = new javax.swing.JLabel();
        numCliente = new javax.swing.JTextField();
        seleccionjLabel = new javax.swing.JLabel();
        NivelAtencionjLabel = new javax.swing.JLabel();
        nAtencion = new javax.swing.JComboBox<>();
        ResolucionjLabel = new javax.swing.JLabel();
        nResolucion = new javax.swing.JComboBox<>();
        RecmendacionjLabel = new javax.swing.JLabel();
        nRecomendacion = new javax.swing.JComboBox<>();
        GuardarButtom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(407, 384));

        titulojLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titulojLabel.setText("Encuesta de Calidad");

        nombrejLabel.setText("Nombre");
        nombrejLabel.setName(""); // NOI18N

        apellidojLabel.setText("Apellido");

        numclienteJLabel.setText("N° de Cliente");

        numCliente.setText("0");

        seleccionjLabel.setText("*Seleccione un puntaje entre 0  y 10.");

        NivelAtencionjLabel.setText("Nivel de Atención");

        nAtencion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        ResolucionjLabel.setText("Nivel de resolución");

        nResolucion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        RecmendacionjLabel.setText("Nivel de Recomendación");

        nRecomendacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        GuardarButtom.setText("GUARDAR");
        GuardarButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(apellidojLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(apellido))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nombrejLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(numclienteJLabel)
                            .addGap(18, 18, 18)
                            .addComponent(numCliente)))
                    .addComponent(seleccionjLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NivelAtencionjLabel)
                            .addComponent(ResolucionjLabel)
                            .addComponent(RecmendacionjLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nRecomendacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GuardarButtom)
                .addGap(163, 163, 163))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulojLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrejLabel)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidojLabel)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numclienteJLabel)
                    .addComponent(numCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(seleccionjLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NivelAtencionjLabel)
                    .addComponent(nAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ResolucionjLabel)
                        .addGap(18, 18, 18)
                        .addComponent(RecmendacionjLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nRecomendacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(GuardarButtom)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarButtomActionPerformed

        Validaciones validar = new Validaciones();

        if (validar.vacio(nombre.getText())) {
            if (validar.vacio(apellido.getText())) {
                if (validar.esMayor(numCliente.getText())) {

                    cliente persona1 = new cliente(nombre.getText(), apellido.getText(), numCliente.getText());

                    encuesta enc1 = new encuesta(nAtencion.toString(), nResolucion.toString(), nRecomendacion.toString());

                    int ate = Integer.parseInt(nAtencion.getSelectedItem().toString());
                    int res = Integer.parseInt(nResolucion.getSelectedItem().toString());
                    int rec = Integer.parseInt(nRecomendacion.getSelectedItem().toString());

                    Promedio pro = new Promedio();
                    pro.proEncu(ate, res, rec);

                    pro.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "INGRESE EL NUMERO DE CLIENTE", "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "INGRESE SU APELLIDO", "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            }
     
        }else{
            JOptionPane.showMessageDialog(null, "INGRESE SU NOMBRE", "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
        }     
    }//GEN-LAST:event_GuardarButtomActionPerformed
    
    /**
     * @param args the command line arguments
     */
    

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuardarButtom;
    private javax.swing.JLabel NivelAtencionjLabel;
    private javax.swing.JLabel RecmendacionjLabel;
    private javax.swing.JLabel ResolucionjLabel;
    private javax.swing.JTextField apellido;
    private javax.swing.JLabel apellidojLabel;
    private javax.swing.JComboBox<String> nAtencion;
    private javax.swing.JComboBox<String> nRecomendacion;
    private javax.swing.JComboBox<String> nResolucion;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel nombrejLabel;
    private javax.swing.JTextField numCliente;
    private javax.swing.JLabel numclienteJLabel;
    private javax.swing.JLabel seleccionjLabel;
    private javax.swing.JLabel titulojLabel;
    // End of variables declaration//GEN-END:variables
}
